### ISSUE TITLE
Failing tests with geopandas and dask main

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/dask-geopandas#135]
There are two failing tests at the moment in the dev build (eg https://github.com/geopandas/dask-geopandas/runs/4912124074?check_suite_focus=true).

In an environment with just dask main, one of the two tests fails: `tests/test_core.py::TestDissolve::test_split_out`. This is caused by https://github.com/dask/dask/pull/8468 which was merged yesterday.

In an environment with just geopandas main, the other test fails: `tests/test_core.py::test_set_geometry_with_dask_geoseries` with

```
______________________________________________________________________________________ test_set_geometry_with_dask_geoseries ______________________________________________________________________________________

    def test_set_geometry_with_dask_geoseries():
        df = pd.DataFrame({"x": [0, 1, 2, 3], "y": [1, 2, 3, 4]})
        dask_obj = dd.from_pandas(df, npartitions=2)
        dask_obj = dask_geopandas.from_dask_dataframe(dask_obj)
>       dask_obj = dask_obj.set_geometry(dask_geopandas.points_from_xy(dask_obj, "x", "y"))

tests/test_core.py:356: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = Dask DataFrame Structure:
                   x      y
npartitions=2              
0              int64  int64
2                ...    ...
3                ...    ...
Dask Name: GeoDataFrame, 4 tasks
key = 'set_geometry'

    def __getattr__(self, key):
        if key in self.columns:
            return self[key]
        else:
>           raise AttributeError("'DataFrame' object has no attribute %r" % key)
E           AttributeError: 'DataFrame' object has no attribute 'set_geometry'

../dask/dask/dataframe/core.py:4268: AttributeError
```

Given the error that might be related to the changes in geopandas related to `_constructor` returning DataFrame vs GeoDataFrame depending geometry columns being present or not. Update: indeed starts to fail with https://github.com/geopandas/geopandas/pull/2060

**Comment by jorisvandenbossche** [comment]
The reason for the second failure is that `dask_geopandas.from_dask_dataframe(ddf)` no longer returns a dask_geopandas.GeoDataFrame, but a dask.dataframe.DataFrame:

https://github.com/geopandas/dask-geopandas/blob/1073e4057023d24795a1b058aa7698d978bc6706/dask_geopandas/core.py#L549-L550

The class is inferred from the class of the individual partitions, and because there is no geometry column present, the above `GeoDataFrame(..)` call will no return a normal DataFrame, and hence dask decides to return a dd.DataFrame.

And in geopandas, we patch pandas.DataFrame to have a `set_geometry` method, but in dask_geopandas we don't (yet) do that.

**Comment by martinfleis** [comment]
The first issue is actually a regression in `dask`, isn't it? Since the same code should work no matter the `split_out` argument.

**Comment by martinfleis** [comment]
xref https://github.com/dask/dask/issues/8611

**Comment by jorisvandenbossche** [comment]
It's certainly caused by a change in dask, but it could also be that the change uncovered a bug in geopandas or dask_geopandas. Try to diagnose it.

**Comment by jorisvandenbossche** [comment]
For the dask-related failure, we can short-term issue a warning to give a hint to the user why it is failing

**Comment by martinfleis** [comment]
Fixed in https://github.com/dask/dask/pull/8643
